language: cpp
os: linux
compiler:
  - gcc
    # - clang
env:
    # - GCC_VERSION=4.9
  - GCC_VERSION=5
# matrix:
#   exclude:
#     - compiler: clang
#       env: GCC_VERSION=4.9
#  allow_failures:
#    - compiler: clang      # until llvm.org apt server is back up
#      env: GCC_VERSION=5   #
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - boost-latest
      # LLVM apt mirror is down
      #- llvm-toolchain-precise-3.7
    packages:
        # - g++-4.9
      - g++-5
      - libeigen3-dev
      - libboost1.55-dev
      - libblas-dev
      - liblapack-dev
      - libtbb-dev
      - cmake
      - cmake-data
# llvm.org apt repo is down
#     - clang-3.7
before_install: 
   - ./bin/build-mpich-$TRAVIS_OS_NAME.sh
   - ./bin/build-libint-$TRAVIS_OS_NAME.sh
   - ./bin/build-TA-$TRAVIS_OS_NAME.sh
script: ./bin/build-$TRAVIS_OS_NAME.sh
after_failure:
  - cat ./_build/libint-2.2.0-beta1/config.log
  - ls $HOME
  - cat ./_build/external/build/madness/CMakeFiles/CMakeOutput.log
  - cat ./_build/external/build/madness/CMakeFiles/CMakeError.log
  - cat ./_build/CMakeFiles/CMakeOutput.log
  - cat ./_build/CMakeFiles/CMakeError.log
