language: cpp
cache: ccache
os: linux
compiler:
  - gcc
  - clang
env:
  - GCC_VERSION=5
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - boost-latest
      - kubuntu-backports
      - llvm-toolchain-precise-3.8
    packages:
      - g++-5
      - libeigen3-dev
      - libboost1.55-all-dev
      - libblas-dev
      - liblapack-dev
      - libtbb-dev
      - clang-3.8
      - cmake
      - cmake-data
before_install: 
     - ./bin/build-mpich-$TRAVIS_OS_NAME.sh
     - ./bin/build-libint-$TRAVIS_OS_NAME.sh
     - ./bin/build-TA-$TRAVIS_OS_NAME.sh
script: ./bin/build-$TRAVIS_OS_NAME.sh
after_failure:
  - cat ./_build/mpqc4/CMakeFiles/CMakeOutput.log
  - cat ./_build/mpqc4/CMakeFiles/CMakeError.log
