language: cpp
cache: ccache
os: linux
compiler:
- gcc
- clang
env:
- GCC_VERSION=5 BUILD_TYPE=Debug
- GCC_VERSION=5 BUILD_TYPE=Release
- GCC_VERSION=6 BUILD_TYPE=Debug
- GCC_VERSION=6 BUILD_TYPE=Release
branches:
  only:
  - master
sudo: true
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=5 BUILD_TYPE=Debug
    - compiler: clang
      env: GCC_VERSION=5 BUILD_TYPE=Release
  allow_failures:
# this results in an ICE when compiling zrhf.cpp
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - boost-latest
    - kubuntu-backports
    - llvm-toolchain-precise-3.8
    - sourceline: 'ppa:kalakris/eigen'
    packages:
    - g++-5
    - g++-6
    - libeigen3-dev
    - libboost1.55-all-dev
    - libblas-dev
    - liblapack-dev
    - libtbb-dev
    - clang-3.8
    - cmake
    - cmake-data
before_install:
- "./bin/build-mpich-$TRAVIS_OS_NAME.sh"
- "./bin/build-libint-$TRAVIS_OS_NAME.sh"
- "./bin/build-TA-$TRAVIS_OS_NAME.sh"
script: "travis_wait 50 ./bin/build-$TRAVIS_OS_NAME.sh"
after_failure:
- cat ./mpqc4_build/CMakeFiles/CMakeOutput.log
- cat ./mpqc4_build/CMakeFiles/CMakeError.log
notifications:
  slack:
    secure: aTBPnV/QUvD5zjB82Gz8MwqtjDcxMuAtGY3m2KM4kD54kxZxPXGC7sHb9e/EOHm0qoudTR8aielY99y9mPH3v/5qXvyQKU3md+aE9i+XB2ewm5WXDUXmr8wS63W+9EflXfFeC1JxantyYkZ9n4itCZP7WlY9x7rMfs/+1P5A0Ew=
