title: MPQC
description: The Massively Parallel Quantum Chemistry (MPQC) platform is a research package for ab initio simulation of the electronic structure of molecules and periodic solids, with primary focus on many-body electronic structure methods, such as coupled-cluster.
google_analytics: 
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
